In [49]:
import pandas as pd
import datetime
from sklearn import datasets
import logging

In [50]:
from evidently.ui.workspace.cloud import CloudWorkspace

from evidently.report import Report
from evidently.metric_preset import DataQualityPreset
from evidently.metric_preset import DataDriftPreset
from evidently.metrics import *
from evidently.test_suite import TestSuite
from evidently.tests import *
from evidently.test_preset import DataDriftTestPreset
from evidently.tests.base_test import TestResult, TestStatus
from src.DataOps.feature_engg import feature_engg_class
from src.ModelOps.model_fit import ModelFit
import wandb

In [51]:
from dotenv import load_dotenv
import os

load_dotenv()
#connecting to evidently cloud workspace using API token
ws = CloudWorkspace(
token=os.getenv('evi_api'),
url="https://app.evidently.cloud")

# #creating a project in the workspace
__project_name__="Test2 Project"
__team_id__="74fdd884-9679-4693-819b-a6695e652e25"

project = ws.create_project(__project_name__,team_id=__team_id__)
project.description = "My project description"
project.save()

Project(id=UUID('03cd4d67-c575-474e-b6ee-a5549b3cfb6a'), name='Test2 Project', description='My project description', dashboard=DashboardConfig(name='Test2 Project', panels=[], tabs=[], tab_id_to_panel_ids={}), team_id=UUID('74fdd884-9679-4693-819b-a6695e652e25'), date_from=None, date_to=None, created_at=datetime.datetime(2024, 7, 3, 16, 29, 19, 983035))

In [52]:
print(project.id)

03cd4d67-c575-474e-b6ee-a5549b3cfb6a

In [53]:
stock_data = feature_engg_class()
data=stock_data.request_stock_price_hist('AAPL')
stock_data.data=data
train,test=stock_data.split(use_prophet=True)

INFO:root:Feature Engineering class initialized
INFO:root:Retrieving stock price data from Alpha Vantage (This may take a while)...
INFO:root:Data has been successfully downloaded...
INFO:root:Storing the retrieved data into a dataframe...
100%|██████████| 1287/1287 [00:01<00:00, 688.38it/s]
INFO:root:Sorting the index and changing column data types...
INFO:root:Data loaded successfully
INFO:root:Data shape: (1287, 7)
INFO:root:Earliest Date:2024-07-03 00:00:00,Latest Date:2024-07-03 00:00:00
INFO:root:Data prepared for Prophet
INFO:root:Data split into train and test successfully
INFO:root:Train shape: 900
INFO:root:Test shape: 387

In [54]:
import yaml
with open('conf/mlops.yaml', 'r') as file:
            config = yaml.safe_load(file)
model_name = config['model_name']
project_name=config['project_name']
model_type=config['model_type']
wandb_entity=config['wandb_entity']
print(model_name,project_name,model_type,wandb_entity)

stock_price_prediction ml-ops-template time-series sakshamgulati123

In [55]:
from prophet.serialize import  model_from_json

run = wandb.init(project=model_name,job_type=model_type)
artifact = run.use_artifact(f'{wandb_entity}/model-registry/{model_name}:latest', type='model')
artifact_dir = artifact.download()
logging.info(f"Artifact downloaded at: {artifact_dir}")
logging.info("Model artifact downloaded")
#load  pickle file
file_path = os.path.join(artifact_dir, 'serialized_model.json')  # specify the correct file path
with open(file_path, 'r') as fin:
    model = model_from_json(fin.read())  # Load model
logging.info("Model loaded from the registry")
y_pred = model.predict(test)

wandb:   1 of 1 files downloaded.
INFO:root:Artifact downloaded at: /Users/sakshamgulati/MLOps_Template/artifacts/run-77xhl9ch-serialized_model.json:v0
INFO:root:Model artifact downloaded
INFO:root:Model loaded from the registry

In [56]:
y_pred

,ds,trend,yhat_lower,yhat_upper,trend_lower,trend_upper,Christmas Day,Christmas Day_lower,Christmas Day_upper,Christmas Day (observed),...,weekly,weekly_lower,weekly_upper,yearly,yearly_lower,yearly_upper,multiplicative_terms,multiplicative_terms_lower,multiplicative_terms_upper,yhat
0,2017-02-10,-2.444415,-96.236969,74.107469,-2.444415,-2.444415,0.0,0.0,0.0,0.0,...,-7.539187,-7.539187,-7.539187,-0.982402,-0.982402,-0.982402,0.0,0.0,0.0,-10.966004
1,2017-02-17,-4.865519,-94.266234,70.571568,-4.865519,-4.865519,0.0,0.0,0.0,0.0,...,-7.539187,-7.539187,-7.539187,0.392142,0.392142,0.392142,0.0,0.0,0.0,-12.012564
2,2017-02-24,-7.286623,-96.484431,65.021874,-7.286623,-7.286623,0.0,0.0,0.0,0.0,...,-7.539187,-7.539187,-7.539187,-0.541140,-0.541140,-0.541140,0.0,0.0,0.0,-15.366950
3,2017-03-03,-9.707727,-101.954842,60.590528,-9.707727,-9.707727,0.0,0.0,0.0,0.0,...,-7.539187,-7.539187,-7.539187,-1.260896,-1.260896,-1.260896,0.0,0.0,0.0,-18.507810
4,2017-03-10,-12.128831,-101.516610,69.369274,-12.128831,-12.128831,0.0,0.0,0.0,0.0,...,-7.539187,-7.539187,-7.539187,0.968726,0.968726,0.968726,0.0,0.0,0.0,-18.699292
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
382,2024-06-07,-927.306164,-1284.047588,-573.648713,-1268.097889,-580.040210,0.0,0.0,0.0,0.0,...,-7.539187,-7.539187,-7.539187,4.166532,4.166532,4.166532,0.0,0.0,0.0,-930.678819
383,2024-06-14,-929.727268,-1310.261242,-608.102051,-1272.066819,-580.445770,0.0,0.0,0.0,0.0,...,-7.539187,-7.539187,-7.539187,-10.543348,-10.543348,-10.543348,0.0,0.0,0.0,-947.809803
384,2024-06-21,-932.148372,-1310.384708,-590.533991,-1276.035748,-580.881688,0.0,0.0,0.0,0.0,...,-7.539187,-7.539187,-7.539187,-21.683830,-21.683830,-21.683830,0.0,0.0,0.0,-961.371389
385,2024-06-28,-934.569476,-1316.613661,-602.549293,-1280.004678,-581.317605,0.0,0.0,0.0,0.0,...,-7.539187,-7.539187,-7.539187,-23.555259,-23.555259,-23.555259,0.0,0.0,0.0,-965.663922
386,2024-07-03,-936.298836,-1297.022304,-586.017486,-1283.281864,-581.534382,0.0,0.0,0.0,0.0,...,11.428931,11.428931,11.428931,-20.115014,-20.115014,-20.115014,0.0,0.0,0.0,-944.984918

In [57]:
ref_dataset = run.use_artifact(f'{wandb_entity}/{model_name}/reference-dataset:latest', type='dataset')
ref_dataset_dir = ref_dataset.download()
logging.info(f"Artifact downloaded at: {ref_dataset_dir}")
logging.info("Reference artifact downloaded")

wandb:   1 of 1 files downloaded.
INFO:root:Artifact downloaded at: /Users/sakshamgulati/MLOps_Template/artifacts/reference-dataset:v5
INFO:root:Reference artifact downloaded

In [58]:
import glob
csv_files = glob.glob(os.path.join(ref_dataset_dir, "*.csv"))
for csv in csv_files:
    reference_data=pd.read_csv(csv)

In [59]:
test

             ds       y
900  2017-02-10  132.12
901  2017-02-17  135.72
902  2017-02-24  136.66
903  2017-03-03  139.78
904  2017-03-10  139.14
...         ...     ...
1282 2024-06-07  196.89
1283 2024-06-14  212.49
1284 2024-06-21  207.49
1285 2024-06-28  210.62
1286 2024-07-03  221.55

[387 rows x 2 columns]

In [60]:
from evidently.pipeline.column_mapping import ColumnMapping
from evidently.report import Report
from evidently.metric_preset import DataDriftPreset, RegressionPreset

target = 'y'
prediction = 'prediction'
# numerical_features = ['open', 'high', 'low', 'adjusted close', 'volume', 'dividend amount']
# categorical_features = ['season', 'holiday', 'workingday', ]#'weathersit']

column_mapping = ColumnMapping()

column_mapping.target = target
column_mapping.prediction = prediction
# column_mapping.datetime_features = 'ds'
column_mapping.datetime='ds'
column_mapping.id = None

In [61]:
regression_performance_report = Report(metrics=[
    RegressionPreset(),
])

regression_performance_report.run(reference_data=reference_data, current_data=test,
                                        column_mapping=column_mapping)

WARNING:root:Column ds have different types in reference object and current datetime64[ns]. Returning type from reference
WARNING:root:Column ds have different types in reference object and current datetime64[ns]. Returning type from reference

In [63]:
with open('conf/mlops.yaml', 'r') as file:
        config = yaml.safe_load(file)
        model_name = config['model_name']
        project_name=config['project_name']
        model_type=config['model_type']
        wandb_entity=config['wandb_entity']

In [64]:
project_name

'ml-ops-template'

In [66]:
projects=ws.search_project(project_name)
projects[0].id

UUID('19726c56-b662-4013-93c8-5fb302e2e263')